export enum MessageType {
    MORNING_POLL = "MORNING_POLL",
    EVENING_POLL = "MORNING_POLL",
    DAILY_PERFORMER = "DAILY_PERFORMER",
    USA_HOLIDAY = "USA_HOLIDAY",
    INDIA_HOLIDAY = "INDIA_HOLIDAY"
}
