name: Deploy to Firebase Functions

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy_functions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: functions/package-lock.json

      - name: Install Dependencies
        run: cd functions && npm ci

      - name: Build Functions
        run: cd functions && npm run build

      - name: Create .env file
        run: |
          cd functions
          cat << EOF > .env
          TELEGRAM_BOT_TOKEN=${{ secrets.TELEGRAM_BOT_TOKEN }}
          GOOGLE_MAPS_API_KEY=${{ secrets.GOOGLE_MAPS_API_KEY }}
          EOF

      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only functions
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          PROJECT_ID: telegram-bot-e91d5
